### ISSUE TITLE
Failed to find addon version number for game version: GameVersion.retail

### ISSUE THREAD

**Issue by Swatto86** [grrttedwards/wow-addon-updater#112] opened 2020-03-03 22:27 UTC
Hello,

I use the script daily to update my WoW addons but today it has stopped working.  I get:

Failed to find addon version number for game version: GameVersion.retail

Is this something to do with cloudflare blocking the requests? Is there any further information I can provide?

Failed to find addon version number for game version: GameVersion.retail

Name                       Prev. Version              New Version                
────                       ─────────────              ───────────                
announce-interrupts        -----                      Unavailable

**Comment by grrttedwards** [comment] 2020-03-03 22:30
Hello! I’m glad to hear you get some use from this code.

Unfortunately my exception handling is bad, so the printout doesn’t tell me much about what you’re seeing. 

Could you tell me which url this is affecting? It’s probably a Curse link, if I had to guess.

**Comment by Swatto86** [comment] 2020-03-03 22:38
Hi - wow that was a quick reply.

Yep you are correct it is the curseforge url it is affecting.

**Comment by theundebruijn** [comment] 2020-03-04 01:27
Same issue here. Also using curse urls for the addon paths.

@grrttedwards thanks for keeping this up to data btw. It's awesome.

**Comment by grrttedwards** [comment] 2020-03-04 01:32
Thanks! I will try to get to debugging this soon.

**Comment by godlike64** [comment] 2020-03-04 14:53
Same here with current master. Let us know if there is anything you would wish us to test.

**Comment by fspy** [comment] 2020-03-04 19:36
Looks like the html structure changed so the script is unable to find new versions.
Maybe it's time to think about a better way of fetching the addons

**Comment by grrttedwards** [comment] 2020-03-04 20:11
Hi all, turns out this was a cloudscraper dependency issue. The version just needed to be updated.

Please try either this branch: https://github.com/grrttedwards/wow-addon-updater/pull/114 and follow the normal procedure for installing dependencies

or just run `pipenv update` on the command line, and then see if you can update your addons normally.

Thanks again. I'm going to add an issue template to give a hint that we should try to `pipenv update` and then re-run the script when an error is seen. This should hopefully make the fix cycle go faster, or even someone else can submit a PR with just the version updates in `Pipfile.lock`

**Comment by fspy** [comment] 2020-03-04 20:21
Same issue. 

Still locked out by Cloudflare reCaptcha. Might need to prompt for a solve or use cookies from a real browser in the requests

**Comment by grrttedwards** [comment] 2020-03-04 20:26
@fspy That's not good :( Both the Travis.ci builds and my local builds are now passing tests and updating addons with the new version. If you run `pipenv run pip freeze` do you see versions matching the following?:

```
beautifulsoup4==4.8.2
certifi==2019.11.28
chardet==3.0.4
cloudscraper==1.2.26
coverage==5.0.3
idna==2.9
requests==2.23.0
requests-toolbelt==0.9.1
soupsieve==2.0
urllib3==1.25.8

```

**Comment by Swatto86** [comment] 2020-03-04 20:28
> Hi all, turns out this was a cloudscraper dependency issue. The version just needed to be updated.
> 
> Please try either this branch: #114 and follow the normal procedure for installing dependencies
> 
> or just run `pipenv update` on the command line, and then see if you can update your addons normally.
> 
> Thanks again. I'm going to add an issue template to give a hint that we should try to `pipenv update` and then re-run the script when an error is seen. This should hopefully make the fix cycle go faster, or even someone else can submit a PR with just the version updates in `Pipfile.lock`

Just tried this and now it works fine for me. Thanks very much

**Comment by Shizato** [comment] 2020-03-04 22:07
@grrttedwards You sir are a gentleman and a scholar. Pulled new build and ran pipenv update and I am now up and running again. Thanks.

**Comment by grrttedwards** [comment] 2020-03-04 22:12
Hi again

I've published a new version [v1.6.1](https://github.com/grrttedwards/wow-addon-updater/releases/tag/v1.6.1) that updates the versions to get the script up and running again, as well as finally adding some much needed logging around errors (which will make it easier for me as well as everyone to help when there is an issue)

I will close this issue as it seems to have worked for 4/5 of the sample so far.

**Closed by grrttedwards** 2020-03-04 22:12 UTC

**Comment by theundebruijn** [comment] 2020-03-04 22:31
Just confirming 1.6.1 works as expected. Thanks again!

**Comment by fspy** [comment] 2020-03-05 00:25
> 
> 
> @fspy That's not good :( Both the Travis.ci builds and my local builds are now passing tests and updating addons with the new version. If you run `pipenv run pip freeze` do you see versions matching the following?:
> 
> ```
> beautifulsoup4==4.8.2
> certifi==2019.11.28
> chardet==3.0.4
> cloudscraper==1.2.26
> coverage==5.0.3
> idna==2.9
> requests==2.23.0
> requests-toolbelt==0.9.1
> soupsieve==2.0
> urllib3==1.25.8
> ```

just double checked this, and they match mine, reset the repo and tried again to no avail.
looks like the issue is on my end

**Comment by grrttedwards** [comment] 2020-03-07 23:17
@fspy Hi, just noticed your edit. Awesome that you got it working; but it is strange you had to do those extra steps. I wonder if you stop connecting to Curse for a while, or get your IP changed or something, if it would work out of the box as expected.

**Comment by crborga** [comment] 2020-03-20 13:00
I am having the same problem as Fspy but making the same changes seems to have gotten it working for me at least temporarily.

**Comment by Kiraan75** [comment] 2020-04-07 06:32
+++FYI+++
Curse was nasty today.
"Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/..."
Running PIPENV UPDATE solved the issue.

**Comment by grrttedwards** [comment] 2020-04-07 22:24
@Kiraan75 Thanks for pointing that out. Have published https://github.com/grrttedwards/wow-addon-updater/releases/tag/v1.6.4 for newcomers, or people can `pipenv update` on their own for this change.

Might need to think about a different solution to the packaging since this continues to be a cat and mouse game with the package version.
